version: "3"
services:
  api:
    container_name: oficina-api
    environment:
      - --spring.datasource.url=jdbc:postgresql://postgres:5432/oficina-1?serverTimezone=America/Sao_Paulo&useLegacyDatetimeCode=false
      - --spring.datasource.username=teste
      - --spring.datasource.password=teste
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint:
      - java
      - -jar
      - /app.jar
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    container_name: postgres-api
    environment:
      - POSTGRES_DB=oficina-1
      - POSTGRES_USER=teste
      - POSTGRES_PASSWORD=teste