version: "3.0"
networks:
  oficina_network:
    driver: bridge
volumes:
  db-data:
    external: true
services:
  api:
    container_name: oficina-api
    environment:
      - --spring.datasource.url=
      - --spring.datasource.username=
      - --spring.datasource.password=
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint:
      - java
      - -jar
      - /app.jar
    ports:
      - "8080:8080"
#    depends_on:
#      - postgres
    networks:
      - oficina-network
#  postgres:
#    image: postgres:latest
#    container_name: postgres-api
#    environment:
#      - POSTGRES_DB=
#      - POSTGRES_USER=admin
#      - POSTGRES_PASSWORD=admin
#      - TZ=GMT
#    networks:
#      oficina_network:
#    volumes:
#      - db-data:./