-- public.course definition

-- Drop table

-- DROP TABLE course;

CREATE TABLE course (
	course_id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	course_code varchar(255) NULL,
	course_created_at timestamp NULL,
	course_is_active bool NOT NULL,
	course_name varchar(25) NULL,
	course_name_normalized varchar(25) NULL,
	course_updated_at timestamp NULL,
	CONSTRAINT course_pkey PRIMARY KEY (course_id),
	CONSTRAINT uk_pbtxfti950chth4yw1wafaf9f UNIQUE (course_code)
);


-- public.users definition

-- Drop table

-- DROP TABLE users;

CREATE TABLE users (
	user_id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	user_birth_date date NOT NULL,
	user_city varchar(255) NOT NULL,
	user_complement varchar(255) NULL,
	user_created_at timestamp NULL,
	user_district varchar(255) NOT NULL,
	user_document varchar(255) NOT NULL,
	user_email varchar(255) NOT NULL,
	user_is_active bool NULL,
	user_name varchar(255) NOT NULL,
	user_normalized_name varchar(255) NOT NULL,
	user_profile int8 NULL,
	user_state varchar(255) NOT NULL,
	user_street varchar(255) NOT NULL,
	user_street_number varchar(10) NOT NULL,
	user_telephone varchar(255) NOT NULL,
	user_zipcode varchar(255) NOT NULL,
	CONSTRAINT uk_33uo7vet9c79ydfuwg1w848f UNIQUE (user_email),
	CONSTRAINT uk_kkuv0csnlsx2m90yrxexk88le UNIQUE (user_document),
	CONSTRAINT users_pkey PRIMARY KEY (user_id)
);


-- public."admin" definition

-- Drop table

-- DROP TABLE "admin";

CREATE TABLE "admin" (
	user_id int8 NOT NULL,
	CONSTRAINT admin_pkey PRIMARY KEY (user_id),
	CONSTRAINT fkq7pdkck9je126wpd9ijw3uwml FOREIGN KEY (user_id) REFERENCES users(user_id)
);


-- public.discipline definition

-- Drop table

-- DROP TABLE discipline;

CREATE TABLE discipline (
	discipline_id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	discipline_code varchar(255) NULL,
	discipline_created_at timestamp NULL,
	discipline_name varchar(25) NULL,
	discipline_normalized_name varchar(25) NULL,
	course_id int8 NOT NULL,
	CONSTRAINT discipline_pkey PRIMARY KEY (discipline_id),
	CONSTRAINT uk_9rjpynvxc29u19eue3g28qauu UNIQUE (discipline_code),
	CONSTRAINT fk60q60lfqgd0gh89sfyqgkuro3 FOREIGN KEY (course_id) REFERENCES course(course_id)
);


-- public.login definition

-- Drop table

-- DROP TABLE login;

CREATE TABLE login (
	user_id int8 NOT NULL,
	login_email varchar(255) NOT NULL,
	login_password varchar(255) NOT NULL,
	CONSTRAINT login_pkey PRIMARY KEY (user_id),
	CONSTRAINT fk5ajtethlf6rmcnipoat0r1qrb FOREIGN KEY (user_id) REFERENCES users(user_id)
);


-- public.professor definition

-- Drop table

-- DROP TABLE professor;

CREATE TABLE professor (
	user_id int8 NOT NULL,
	course_id int8 NOT NULL,
	CONSTRAINT professor_pkey PRIMARY KEY (user_id),
	CONSTRAINT fk61e8vtqmh2l1p3fiiildvva6t FOREIGN KEY (user_id) REFERENCES users(user_id),
	CONSTRAINT fktn8tj1sjq1m5h52qofiq1jwsq FOREIGN KEY (course_id) REFERENCES course(course_id)
);


-- public.student definition

-- Drop table

-- DROP TABLE student;

CREATE TABLE student (
	user_id int8 NOT NULL,
	student_code uuid NULL,
	course_id int8 NULL,
	CONSTRAINT student_pkey PRIMARY KEY (user_id),
	CONSTRAINT fkdfypyqt0stgfc0aij9kcxm99s FOREIGN KEY (course_id) REFERENCES course(course_id),
	CONSTRAINT fkk0thg920a3xk3v59yjbsatw1l FOREIGN KEY (user_id) REFERENCES users(user_id)
);


-- public."class" definition

-- Drop table

-- DROP TABLE "class";

CREATE TABLE "class" (
	class_id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	class_is_active bool NULL,
	course_id int8 NULL,
	professor_id int8 NULL,
	CONSTRAINT class_pkey PRIMARY KEY (class_id),
	CONSTRAINT fklsxcyh4sq20727qj0clvah8dg FOREIGN KEY (course_id) REFERENCES course(course_id),
	CONSTRAINT fkp0uvjxki70ibxj65gwh76l6gd FOREIGN KEY (professor_id) REFERENCES professor(user_id)
);


-- public.grade definition

-- Drop table

-- DROP TABLE grade;

CREATE TABLE grade (
	class_id int8 NOT NULL,
	grade_id varchar(255) NOT NULL,
	student_id int8 NOT NULL,
	grade_score float8 NULL,
	CONSTRAINT grade_pkey PRIMARY KEY (class_id, grade_id, student_id),
	CONSTRAINT fk4t8jgswbxdikjdrft6an8ntbw FOREIGN KEY (class_id) REFERENCES "class"(class_id),
	CONSTRAINT fk5secqnjjwgh9wxk4h1xwgj1n0 FOREIGN KEY (student_id) REFERENCES student(user_id)
);