insert into course (course_id, course_name, course_name_normalized, course_code, course_is_active) values(6, 'curso 1', 'curso_1', 'AS31B', true) ON CONFLICT DO NOTHING;
insert into course (course_id, course_name, course_name_normalized, course_code, course_is_active) values(2, 'curso 2', 'curso_2', 'AS31C', true) ON CONFLICT DO NOTHING;
insert into course (course_id, course_name, course_name_normalized, course_code, course_is_active) values(4, 'curso 3', 'curso_3', 'AS31D', true) ON CONFLICT DO NOTHING;
insert into course (course_id, course_name, course_name_normalized, course_code, course_is_active) values(5, 'curso 4', 'curso_4', 'AS31E', false) ON CONFLICT DO NOTHING;

insert into discipline (discipline_id, discipline_code, discipline_name, discipline_normalized_name, course_id) values (1, '123', 'teste', 'teste', 2) ON CONFLICT DO NOTHING;
insert into discipline (discipline_id, discipline_code, discipline_name, discipline_normalized_name, course_id) values (2, '1234', 'teste1', 'teste1', 2) ON CONFLICT DO NOTHING;
insert into discipline (discipline_id, discipline_code, discipline_name, discipline_normalized_name, course_id) values (3, '1235', 'teste2', 'teste2', 2) ON CONFLICT DO NOTHING;
insert into discipline (discipline_id, discipline_code, discipline_name, discipline_normalized_name, course_id) values (4, '1236', 'teste3', 'teste3', 2) ON CONFLICT DO NOTHING;


insert into users (user_id, user_city, user_complement, user_district, user_document, user_email, user_is_active, user_name, user_normalized_name, user_profile, user_state, user_street, user_street_number, user_telephone, user_zipcode, user_birth_date) VALUES (11, 'cidade1', NULL, 'bairro1', '123456', 'teste1@gmail.com', true, 'teste1', 'teste1', 1, 'estado1', 'rua1', '123', '22999303392', '28960000', '2022-01-15') ON CONFLICT DO NOTHING;
insert into users (user_id, user_city, user_complement, user_district, user_document, user_email, user_is_active, user_name, user_normalized_name, user_profile, user_state, user_street, user_street_number, user_telephone, user_zipcode, user_birth_date) VALUES (2, 'cidade1', NULL, 'bairro1', '123457', 'teste2@gmail.com', true, 'teste2', 'teste2', 1, 'estado1', 'rua1', '123', '22999303392', '28960000', '2022-01-15') ON CONFLICT DO NOTHING;
insert into users (user_id, user_city, user_complement, user_district, user_document, user_email, user_is_active, user_name, user_normalized_name, user_profile, user_state, user_street, user_street_number, user_telephone, user_zipcode, user_birth_date) VALUES (3, 'cidade1', NULL, 'bairro1', '123458', 'teste3@gmail.com', true, 'teste3', 'teste3', 1, 'estado1', 'rua1', '123', '22999303392', '28960000', '2022-01-15') ON CONFLICT DO NOTHING;
insert into users (user_id, user_city, user_complement, user_district, user_document, user_email, user_is_active, user_name, user_normalized_name, user_profile, user_state, user_street, user_street_number, user_telephone, user_zipcode, user_birth_date) VALUES (4, 'cidade1', NULL, 'bairro1', '123459', 'teste4@gmail.com', true, 'teste4', 'teste4', 1, 'estado1', 'rua1', '123', '22999303392', '28960000', '2022-01-15') ON CONFLICT DO NOTHING;