    CREATE TABLE curso (
        curso_id int8 PRIMARY KEY,
        curso_name VARCHAR(25),
        curso_name_normalized VARCHAR(25)
)

CREATE TABLE disciplina (
  disciplina_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   disciplina_code VARCHAR(255),
   disciplina_name VARCHAR(255),
   disciplina_name_normalized VARCHAR(255),
   curso_id BIGINT NOT NULL,
   CONSTRAINT pk_disciplina PRIMARY KEY (disciplina_id)
);

ALTER TABLE disciplina ADD CONSTRAINT FK_DISCIPLINA_ON_CURSO FOREIGN KEY (curso_id) REFERENCES curso (curso_id);